# Generated by Django 5.1.4 on 2024-12-09 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created time')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('code', models.TextField()),
                ('linenos', models.BooleanField(default=False)),
                ('language', models.CharField(choices=[('py', 'python'), ('js', 'javascript')], default='python', max_length=100)),
                ('style', models.CharField(choices=[('friendly', 'friendly'), ('native', 'native')], default='friendly', max_length=100)),
            ],
            options={
                'verbose_name': 'Snippet',
                'ordering': ['created'],
            },
        ),
    ]
