# Generated by Django 5.1.4 on 2024-12-13 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_works'),
    ]

    operations = [
        migrations.AddField(
            model_name='works',
            name='snippets',
            field=models.ManyToManyField(to='snippets.snippet'),
        ),
    ]
