# Generated by Django 5.1.4 on 2024-12-13 07:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0005_alter_works_creators'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='creators',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
