# Generated by Django 5.1.4 on 2024-12-13 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("snippets", "0007_alter_works_creators"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="works",
            options={"ordering": ["title"]},
        ),
    ]
