# Generated by Django 5.1.4 on 2024-12-13 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snippets", "0008_alter_works_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("image", models.ImageField(null=True, upload_to="works/")),
                ("snippets", models.ManyToManyField(to="snippets.snippet")),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.DeleteModel(
            name="Works",
        ),
    ]
