# Generated by Django 5.1.4 on 2024-12-13 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snippets", "0010_project_creators"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="snippets",
            field=models.ManyToManyField(blank=True, to="snippets.snippet"),
        ),
    ]
