# Generated by Django 5.1.4 on 2024-12-13 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("snippets", "0011_alter_project_snippets"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="creators",
        ),
    ]
